version: '3.8'
services:
  backend:
    container_name: backend
    build:
      context: .
    depends_on:
      - db
    ports:
      - "${BACKEND_EXTERNAL_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DATABASE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - postgres-network      
  
  db:
    container_name: db
    image: postgres
    user: "${USERID}:${GROUPID}"
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - "${DATABASE_EXTERNAL_PORT}:5432"
    volumes:
      - ./docker/volumes/data:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge